### ISSUE TITLE
Error during cp based on the README

### ISSUE THREAD

**Issue by goldyfruit** [by/RT-Kernel#2]
Hi,

Thanks for the procedure, I tried it but got an error during the `cp`m the command doesn't match the previous `mkdir`.

```
sudo mkdir /boot/firmware/NTP
sudo mkdir /boot/NTP/firmware/overlays-NTP
```
Error:
```
goldyfruit@rpi4b:~/linux $ sudo cp arch/arm64/boot/dts/broadcom/*.dtb /boot/firmware/RT/; sudo cp arch/arm64/boot/dts/overlays/*.dtb* /boot/firmware/NTP/overlays-RT/; sudo cp arch/arm64/boot/dts/overlays/README /boot/firmware/NTP/overlays-RT/; sudo cp arch/arm64/boot/Image.gz /boot/firmware/kernel8-RT.img
cp: target '/boot/firmware/NTP/overlays-RT/': No such file or directory
cp: cannot create regular file '/boot/firmware/NTP/overlays-RT/': No such file or directory
```

**Comment by by** [comment]
Thanks and I've corrected the directory mixup of /boot/NTP/firmware, which should be /boot/firmware/NTP.

As you've substituted RT for NTP in your copy, you need to create /boot/firmware/RT and /boot/RT/firmware/overlays-RT first.

**Comment by goldyfruit** [comment]
> Thanks and I've corrected the directory mixup of /boot/NTP/firmware, which should be /boot/firmware/NTP.
> 
> As you've substituted RT for NTP in your copy, you need to create /boot/firmware/RT and /boot/RT/firmware/overlays-RT first.

Indeed, I typo during the copy/paste.

I can see as well `kernel=/kernel8-ntp.img` but the `cp` is uppercase, does it have an impact?

```
sudo cp arch/arm64/boot/Image.gz /boot/firmware/kernel8-NTP.img
```

Thanks @by  :+1:

**Comment by by** [comment]
Corrected as well, thanks!

**Comment by goldyfruit** [comment]
Thanks
