### ISSUE TITLE
u128 compile error

### ISSUE THREAD

**Issue by markwinger** [by/RT-Kernel#5]
I tried to follow the instructions but when I ran the wget of the patch it failed.  Checking ../project/rt the patch-6.10-rc3-rt5 did not exist.  But found patch-6.10-rc4-rt6 so i used that as a target.  All work find until I get to building the kernel.  It then fails with many errors.  example:

./arch/arm64/include/asm/atomic_ll_sc.h:298:2: error: unknown type name 'u128' 

The error appears many times but all seem to originate from 2 heard files, atomic_ll_sc.h and cmpxchg.h.

I am on a rpi5 with 4  gig, and the kernel is 6.1.21-x8.gcc is version 10.2.1.  

First-is my substitution of rc4-rt6 the correct thing?  If so, any ideas how fix this build issue?

**Comment by by** [comment]
Thanks for trying out my instructions! – The RT kernel patch needs to fit to the kernel: kernel 6.10-rc4 fits to patch 6.10-rc4-rt6, for example; for kernel 6.1, you need one from https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/6.1/
https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/ gives you an overview about all RT-kernel patches available.

**Comment by markwinger** [comment]
I started from scratch with a new SD card and os.  The build went without a hitch.  Thanks.
